"""The checked-in protobuf codegen has no consumer and needs a drift guard — REG-056.

``aegis/core/audit_node_pb2.py`` is generated code tracked in the tree. Nothing
imports it, and before this module nothing could regenerate or verify it: there
was no ``protoc`` invocation anywhere in the repository, no Makefile target, and
no ``buf``/``grpc_tools`` configuration. Tracked generated code with no guard is
a silent-drift hazard — the ``.proto`` can be edited, or the runtime can move
past the generator, and ``from aegis.core import audit_node_pb2`` keeps working
until the day it does not.

These tests pin the three properties that make the pair trustworthy *without*
requiring protoc at test time, which is the part CI can assert:

1. the checked-in descriptor and the ``.proto`` describe the same message;
2. the module imports and a message round-trips under the installed runtime;
3. a regeneration path exists and names the tool it needs.
"""

from __future__ import annotations

import importlib
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
PROTO_PATH = REPO_ROOT / "aegis" / "core" / "audit_node.proto"
GENERATED_PATH = REPO_ROOT / "aegis" / "core" / "audit_node_pb2.py"
REGEN_SCRIPT = REPO_ROOT / "scripts" / "regenerate_protobuf.sh"

# proto3 scalar type name -> google.protobuf.descriptor.FieldDescriptor type.
PROTO_TYPE_TO_DESCRIPTOR = {
    "double": 1,  # TYPE_DOUBLE
    "float": 2,  # TYPE_FLOAT
    "int64": 3,  # TYPE_INT64
    "uint64": 4,  # TYPE_UINT64
    "int32": 5,  # TYPE_INT32
    "bool": 8,  # TYPE_BOOL
    "string": 9,  # TYPE_STRING
    "bytes": 12,  # TYPE_BYTES
}

_FIELD_RE = re.compile(
    r"^\s*(?P<label>repeated\s+)?(?P<type>\w+)\s+(?P<name>\w+)\s*=\s*(?P<number>\d+)\s*;",
    re.MULTILINE,
)
_VERSION_RE = re.compile(r"^# Protobuf Python Version: (?P<version>[0-9.]+)$", re.MULTILINE)
_IMPORT_RE = re.compile(r"^\s*(?:from|import)\s+[\w.]*audit_node_pb2", re.MULTILINE)


def _proto_fields() -> dict[str, tuple[int, int]]:
    """Return {field name: (number, descriptor type)} parsed from the .proto."""
    text = PROTO_PATH.read_text(encoding="utf-8")
    fields: dict[str, tuple[int, int]] = {}
    for match in _FIELD_RE.finditer(text):
        assert match.group("label") is None, (
            "repeated fields are not handled by this comparison; extend the test "
            "before adding one to the message"
        )
        type_name = match.group("type")
        assert type_name in PROTO_TYPE_TO_DESCRIPTOR, f"unmapped proto type {type_name!r}"
        fields[match.group("name")] = (
            int(match.group("number")),
            PROTO_TYPE_TO_DESCRIPTOR[type_name],
        )
    assert fields, f"no fields parsed from {PROTO_PATH}"
    return fields


def _checked_in_module():
    return importlib.import_module("aegis.core.audit_node_pb2")


def test_proto_source_and_checked_in_descriptor_agree():
    """Editing the .proto without regenerating must fail here, not in production."""
    expected = _proto_fields()
    descriptor = _checked_in_module().AuditNodeProto.DESCRIPTOR

    actual = {
        field.name: (field.number, field.type) for field in descriptor.fields
    }
    assert actual == expected, (
        "the checked-in descriptor and audit_node.proto disagree; regenerate with "
        "scripts/regenerate_protobuf.sh (field name, number and scalar type must match)"
    )
    assert descriptor.full_name == "aegis.core.AuditNodeProto"


def test_message_round_trips_under_the_installed_runtime():
    """The generated code must still work with the protobuf the tree pins."""
    module = _checked_in_module()
    message = module.AuditNodeProto(
        state_id="state-1",
        timestamp=1.5,
        entropy=0.25,
        payload=b"\x00\x01payload",
        tenant_id="tenant-a",
        sampling_params_json='{"temperature":0.0}',
        prev_hash="0" * 64,
        merkle_root="1" * 64,
        signature=b"sig",
    )
    restored = module.AuditNodeProto()
    restored.ParseFromString(message.SerializeToString())
    assert restored == message
    assert restored.payload == b"\x00\x01payload"


def test_generated_file_declares_its_generator():
    """The banner is the only record of which generator wrote the checked-in bytes."""
    text = GENERATED_PATH.read_text(encoding="utf-8")
    assert text.startswith("# Generated by the protocol buffer compiler.  DO NOT EDIT!")
    assert "# source: audit_node.proto" in text
    match = _VERSION_RE.search(text)
    assert match is not None, "the generated banner must record its protobuf version"

    import google.protobuf  # noqa: PLC0415 - version probe, import cost is trivial

    generated_major = int(match.group("version").split(".")[0])
    runtime_major = int(google.protobuf.__version__.split(".")[0])
    assert runtime_major >= generated_major, (
        f"runtime protobuf {google.protobuf.__version__} is older than the generator "
        f"{match.group('version')} that wrote the checked-in file; regenerate with "
        "scripts/regenerate_protobuf.sh"
    )


def test_regeneration_path_exists_and_names_its_tool():
    """Before REG-056 there was no way to regenerate this file; keep it that way."""
    assert REGEN_SCRIPT.exists(), (
        "scripts/regenerate_protobuf.sh is the only regeneration path for the "
        "checked-in descriptor; do not delete it without deleting the generated file"
    )
    script = REGEN_SCRIPT.read_text(encoding="utf-8")
    assert "grpc_tools.protoc" in script
    assert "aegis/core/audit_node.proto" in script
    assert "python_out" in script


def test_generated_module_has_no_in_tree_consumer():
    """Documents the registry's premise: this module is unwired today.

    If a consumer appears, this test is the place to record it — the row that
    closed REG-056 asserted the module has none, and a silent change to that
    would change what the row means. Import statements only: a lazy
    ``importlib`` load would not be caught here, and the reachability gate
    (``scripts/verify_import_reachability.py``) is what covers that.
    """
    importers: list[str] = []
    for path in REPO_ROOT.rglob("*.py"):
        if ".venv" in path.parts or path == GENERATED_PATH or path == Path(__file__):
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):  # pragma: no cover - unreadable file
            continue
        if _IMPORT_RE.search(text):
            importers.append(str(path.relative_to(REPO_ROOT)))

    assert importers == [], (
        "audit_node_pb2 now has an in-tree consumer "
        f"({', '.join(sorted(importers))}); update REG-056's evidence rather than "
        "deleting this assertion"
    )
