// Aegis Latent Core on one Azure VM: VM + Premium data disk for the WAL + Caddy TLS.
// Deploy with the kit generated by deploy/azure/kit-creator, or directly:
//   az deployment group create -g <rg> -f main.bicep -p sshPublicKey=@key.pub
// No secret is a parameter: every secret is generated on the VM at first boot.
targetScope = 'resourceGroup'

@description('Prefix for every resource name (3-20 lowercase letters, digits, hyphen).')
@minLength(3)
@maxLength(20)
param name string = 'aegis'

param location string = resourceGroup().location

@description('Globally unique-per-region DNS label: <label>.<region>.cloudapp.azure.com')
@minLength(3)
@maxLength(40)
param dnsLabel string

@description('VM size. Standard_B2als_v2 is the 2 vCPU / 4 GiB minimum the AKS overlay also uses.')
param vmSize string = 'Standard_B2als_v2'

@description('Admin user for SSH (key auth only; passwords are disabled).')
param adminUsername string = 'azureuser'

@description('SSH public key (contents of an .pub file).')
param sshPublicKey string

@description('CIDR allowed to reach SSH. Empty string opens no SSH rule.')
param sshSourceCidr string = ''

@description('Availability zone (1-3), or empty for a regional VM in regions/SKUs without zones.')
param zone string = ''

@description('WAL data disk size in GiB (Premium SSD).')
@minValue(4)
@maxValue(1024)
param dataDiskGb int = 32

@description('Gateway image. Pin a digest (repo@sha256:...) for reproducibility.')
param image string = 'ghcr.io/juanlunaia/aegis-latent-core:5.0.1'

@allowed(['openai', 'anthropic', 'gemini', 'openrouter'])
param provider string = 'openai'

param backendUrl string = 'https://api.openai.com'

@description('Monthly budget in USD for this resource group; 0 disables the budget.')
param budgetUsd int = 0

@description('Alert e-mail for the budget (required when budgetUsd > 0).')
param budgetEmail string = ''

@description('First day of the current month, yyyy-MM-01 (set by deploy.sh).')
param budgetStart string = '2026-01-01'

param tags object = { app: 'aegis-latent-core', managedBy: 'aegis-azure-kit' }

var fqdn = '${dnsLabel}.${location}.cloudapp.azure.com'
var zones = empty(zone) ? [] : [zone]

var cloudInit = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(
  loadTextContent('assets/cloud-init.yaml'),
  '__IMAGE__', image),
  '__FQDN__', fqdn),
  '__PROVIDER__', provider),
  '__BACKEND_URL__', backendUrl),
  '__COMPOSE_B64__', base64(loadTextContent('assets/docker-compose.yml'))),
  '__CADDY_B64__', base64(loadTextContent('assets/Caddyfile'))),
  '__UNIT_B64__', base64(loadTextContent('assets/aegis.service'))),
  '__DISK_B64__', base64(loadTextContent('assets/aegis-prepare-disk'))),
  '__SECRETS_B64__', base64(loadTextContent('assets/aegis-bootstrap-secrets'))),
  '__SETKEY_B64__', base64(loadTextContent('assets/aegis-set-backend-key'))),
  '__SHOWKEY_B64__', base64(loadTextContent('assets/aegis-show-client-key')))

var sshRule = empty(sshSourceCidr) ? [] : [
  {
    name: 'ssh'
    properties: {
      priority: 100
      direction: 'Inbound'
      access: 'Allow'
      protocol: 'Tcp'
      sourceAddressPrefix: sshSourceCidr
      sourcePortRange: '*'
      destinationAddressPrefix: '*'
      destinationPortRange: '22'
    }
  }
]

resource nsg 'Microsoft.Network/networkSecurityGroups@2023-09-01' = {
  name: '${name}-nsg'
  location: location
  tags: tags
  properties: {
    securityRules: concat(sshRule, [
      {
        name: 'https'
        properties: {
          priority: 200
          direction: 'Inbound'
          access: 'Allow'
          protocol: 'Tcp'
          sourceAddressPrefix: 'Internet'
          sourcePortRange: '*'
          destinationAddressPrefix: '*'
          destinationPortRanges: ['80', '443'] // 80 is needed for the ACME HTTP-01 challenge and redirect
        }
      }
    ])
  }
}

resource vnet 'Microsoft.Network/virtualNetworks@2023-09-01' = {
  name: '${name}-vnet'
  location: location
  tags: tags
  properties: {
    addressSpace: { addressPrefixes: ['10.60.0.0/24'] }
    subnets: [
      {
        name: 'default'
        properties: {
          addressPrefix: '10.60.0.0/26'
          networkSecurityGroup: { id: nsg.id }
        }
      }
    ]
  }
}

resource pip 'Microsoft.Network/publicIPAddresses@2023-09-01' = {
  name: '${name}-pip'
  location: location
  tags: tags
  sku: { name: 'Standard' }
  zones: zones
  properties: {
    publicIPAllocationMethod: 'Static'
    dnsSettings: { domainNameLabel: dnsLabel }
  }
}

resource nic 'Microsoft.Network/networkInterfaces@2023-09-01' = {
  name: '${name}-nic'
  location: location
  tags: tags
  properties: {
    ipConfigurations: [
      {
        name: 'ipconfig1'
        properties: {
          subnet: { id: vnet.properties.subnets[0].id }
          privateIPAllocationMethod: 'Dynamic'
          publicIPAddress: { id: pip.id }
        }
      }
    ]
  }
}

resource dataDisk 'Microsoft.Compute/disks@2023-10-02' = {
  name: '${name}-wal'
  location: location
  tags: tags
  zones: zones
  sku: { name: 'Premium_LRS' }
  properties: {
    creationData: { createOption: 'Empty' }
    diskSizeGB: dataDiskGb
  }
}

resource vm 'Microsoft.Compute/virtualMachines@2024-03-01' = {
  name: '${name}-vm'
  location: location
  tags: tags
  zones: zones
  properties: {
    hardwareProfile: { vmSize: vmSize }
    securityProfile: {
      securityType: 'TrustedLaunch'
      uefiSettings: { secureBootEnabled: true, vTpmEnabled: true }
    }
    storageProfile: {
      imageReference: {
        publisher: 'Canonical'
        offer: 'ubuntu-24_04-lts'
        sku: 'server'
        version: 'latest'
      }
      osDisk: {
        createOption: 'FromImage'
        diskSizeGB: 32
        managedDisk: { storageAccountType: 'StandardSSD_LRS' }
        deleteOption: 'Delete'
      }
      dataDisks: [
        {
          lun: 0
          createOption: 'Attach'
          managedDisk: { id: dataDisk.id }
          deleteOption: 'Detach' // evidence outlives the VM unless the resource group is deleted
        }
      ]
    }
    osProfile: {
      computerName: '${name}-vm'
      adminUsername: adminUsername
      customData: base64(cloudInit)
      linuxConfiguration: {
        disablePasswordAuthentication: true
        ssh: {
          publicKeys: [
            { path: '/home/${adminUsername}/.ssh/authorized_keys', keyData: sshPublicKey }
          ]
        }
      }
    }
    networkProfile: { networkInterfaces: [{ id: nic.id, properties: { deleteOption: 'Delete' } }] }
  }
}

resource budget 'Microsoft.Consumption/budgets@2023-11-01' = if (budgetUsd > 0) {
  name: '${name}-monthly'
  properties: {
    category: 'Cost'
    amount: budgetUsd
    timeGrain: 'Monthly'
    timePeriod: { startDate: budgetStart }
    notifications: {
      actual50: { enabled: true, operator: 'GreaterThan', threshold: 50, contactEmails: [budgetEmail], thresholdType: 'Actual' }
      actual80: { enabled: true, operator: 'GreaterThan', threshold: 80, contactEmails: [budgetEmail], thresholdType: 'Actual' }
      actual95: { enabled: true, operator: 'GreaterThan', threshold: 95, contactEmails: [budgetEmail], thresholdType: 'Actual' }
      forecast100: { enabled: true, operator: 'GreaterThan', threshold: 100, contactEmails: [budgetEmail], thresholdType: 'Forecasted' }
    }
  }
}

output fqdn string = fqdn
output url string = 'https://${fqdn}'
output vmName string = vm.name
