"use client";

import { parseInclusionProof, verifyInclusionHash, type InclusionProofV1 } from "@aegis-latent/sdk/proof";
import { useState } from "react";

import type { ProofResponse } from "@/lib/contracts";

type LookupState =
  | {readonly kind: "idle"}
  | {readonly kind: "loading"}
  | {readonly kind: "error"; readonly message: string}
  | {readonly kind: "ready"; readonly data: ProofResponse; readonly valid: boolean; readonly transcript: readonly string[]};
type SandboxState =
  | {readonly kind: "idle"}
  | {readonly kind: "result"; readonly valid: boolean; readonly transcript: readonly string[]}
  | {readonly kind: "error"; readonly message: string};

function hex(buffer: ArrayBuffer): string {
  return Array.from(new Uint8Array(buffer), (byte) => byte.toString(16).padStart(2, "0")).join("");
}

async function hashAscii(value: string): Promise<string> {
  return hex(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)));
}

async function proofTranscript(leafHash: string, proof: InclusionProofV1): Promise<string[]> {
  const transcript: string[] = [`Leaf digest: ${leafHash}`];
  let current = leafHash;
  for (const [index, step] of proof.path.entries()) {
    const input = step.direction === "R" ? current + step.sibling_hash : step.sibling_hash + current;
    current = await hashAscii(input);
    transcript.push(`Level ${index + 1}: SHA-256(asciihex(${step.direction === "R" ? "current || sibling" : "sibling || current"})) = ${current}`);
  }
  transcript.push(`Containing peak: ${current}`);
  transcript.push(`Bagged root: SHA-256(asciihex(ordered peaks)) = ${await hashAscii(proof.peaks.map((peak) => peak.hash).join(""))}`);
  return transcript;
}

export function MMRExplorer() {
  const [stateId, setStateId] = useState("");
  const [state, setState] = useState<LookupState>({kind: "idle"});
  async function lookup(): Promise<void> {
    const id = stateId.trim();
    if (!id) { setState({kind: "error", message: "Enter a request/state identifier."}); return; }
    setState({kind: "loading"});
    try {
      const response = await fetch(`/api/aegis/proof?state_id=${encodeURIComponent(id)}`, {cache: "no-store"});
      const value = await response.json() as ProofResponse & {error?: string};
      if (!response.ok) throw new Error(value.error ?? "Proof unavailable");
      const parsed = parseInclusionProof(value.proof);
      const [valid, transcript] = await Promise.all([
        verifyInclusionHash(value.leaf_hash, parsed, value.root),
        proofTranscript(value.leaf_hash, parsed),
      ]);
      setState({kind: "ready", data: value, valid, transcript});
    } catch (error: unknown) {
      setState({kind: "error", message: error instanceof Error ? error.message : "Proof unavailable"});
    }
  }
  return <>
    <form className="toolbar" onSubmit={(event) => { event.preventDefault(); void lookup(); }}>
      <div><label htmlFor="state-id">Request or state identifier</label><input id="state-id" required maxLength={256} value={stateId} onChange={(event) => setStateId(event.target.value)}/></div>
      <button type="submit" disabled={state.kind === "loading"}>Verify proof</button>
    </form>
    {state.kind === "idle" && <section className="notice"><h2>No proof loaded</h2><p>Enter a real request identifier. No proof or root is generated by this interface.</p></section>}
    {state.kind === "loading" && <p aria-live="polite">Retrieving and independently verifying proof…</p>}
    {state.kind === "error" && <section className="notice error" role="alert"><h2>Proof unavailable</h2><p>{state.message}</p></section>}
    {state.kind === "ready" && <ProofResult data={state.data} valid={state.valid} transcript={state.transcript}/>} 
    <VerificationSandbox/>
  </>;
}

function ProofResult({data, valid, transcript}: Readonly<{data: ProofResponse; valid: boolean; transcript: readonly string[]}>) {
  const parsed = parseInclusionProof(data.proof);
  const [selected, setSelected] = useState(true);
  return <section aria-labelledby="proof-result">
    <h2 id="proof-result">Verification result</h2>
    <p className={`status ${valid ? "good" : "bad"}`} aria-live="polite">{valid ? "Valid inclusion proof" : "Invalid inclusion proof"}</p>
    <p>This verifies inclusion of the disclosed leaf digest in the named root. It does not independently establish event truth, time, or legal status.</p>
    <div className="grid"><div className="card"><h3>Leaf</h3><p className="hash">{data.leaf_hash}</p><p>Ordinal {data.leaf_index} of {data.leaf_count}</p></div><div className="card"><h3>Root</h3><p className="hash">{data.root}</p><p>Signature: {data.signature_scheme}; {data.signature_status}</p></div></div>
    <svg viewBox={`0 0 ${Math.max(640, (parsed.path.length + parsed.peaks.length + 1) * 110)} 190`} role="img" aria-labelledby="mmr-title mmr-desc">
      <title id="mmr-title">Merkle Mountain Range inclusion path and ordered peaks</title><desc id="mmr-desc">Select the disclosed leaf to highlight its sibling path to containing peak {parsed.peak_index + 1}.</desc>
      <g transform="translate(55 135)" role="button" tabIndex={0} aria-label="Disclosed leaf; toggle proof path" onClick={() => setSelected((value) => !value)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") setSelected((value) => !value); }}><circle r="32" fill="#1d6078" stroke="#61dafb"/><text textAnchor="middle" fill="#eef5ff" y="5">leaf</text></g>
      {parsed.path.map((step, index) => <g key={`${step.sibling_hash}-${index}`} transform={`translate(${165 + index * 100} ${135 - (index + 1) * 24})`}><line x1="-78" y1="20" x2="-30" y2="4" stroke={selected ? "#61dafb" : "#42566d"} strokeWidth={selected ? 4 : 2}/><circle r="26" fill={selected ? "#1d6078" : "#253c55"} stroke="#61dafb"/><text textAnchor="middle" fill="#eef5ff" y="5">{step.direction}{index + 1}</text></g>)}
      {parsed.peaks.map((peak, index) => <g key={peak.hash} transform={`translate(${180 + parsed.path.length * 100 + index * 90} 55)`}><circle r="28" fill={index === parsed.peak_index && selected ? "#1d6078" : "#253c55"} stroke="#61dafb"/><text textAnchor="middle" fill="#eef5ff" y="5">h{peak.height}</text></g>)}
    </svg>
    <h3>Hash-by-hash transcript</h3><ol>{transcript.map((line) => <li className="proof-step hash" key={line}>{line}</li>)}</ol>
    <h3>Ordered peaks</h3><ol>{parsed.peaks.map((peak, index) => <li key={peak.hash}>Peak {index + 1}, height {peak.height}: <span className="hash">{peak.hash}</span></li>)}</ol>
  </section>;
}

function VerificationSandbox() {
  const [leaf, setLeaf] = useState("");
  const [root, setRoot] = useState("");
  const [proofJson, setProofJson] = useState("");
  const [state, setState] = useState<SandboxState>({kind: "idle"});
  async function verify(): Promise<void> {
    try {
      const proof = parseInclusionProof(JSON.parse(proofJson) as unknown);
      const [valid, transcript] = await Promise.all([verifyInclusionHash(leaf.trim(), proof, root.trim()), proofTranscript(leaf.trim(), proof)]);
      setState({kind: "result", valid, transcript});
    } catch (error: unknown) {
      setState({kind: "error", message: error instanceof Error ? error.message : "Malformed proof input"});
    }
  }
  return <section aria-labelledby="sandbox-title"><h2 id="sandbox-title">Offline verification sandbox</h2><p>Paste only evidence you intend to disclose in this browser session. Verification uses Web Crypto locally; this form does not send the values to Aegis.</p>
    <label htmlFor="sandbox-leaf">Leaf SHA-256</label><input id="sandbox-leaf" className="hash" value={leaf} onChange={(event) => setLeaf(event.target.value)} maxLength={64}/>
    <label htmlFor="sandbox-root">Trusted MMR root</label><input id="sandbox-root" className="hash" value={root} onChange={(event) => setRoot(event.target.value)} maxLength={64}/>
    <label htmlFor="sandbox-proof">aegis-mmr-inclusion-v1 JSON proof</label><textarea id="sandbox-proof" className="hash" value={proofJson} onChange={(event) => setProofJson(event.target.value)}/>
    <button type="button" onClick={() => void verify()}>Verify locally</button>
    {state.kind === "error" && <p role="alert">{state.message}</p>}
    {state.kind === "result" && <div className="notice" role="status"><h3>{state.valid ? "Valid inclusion proof" : "Invalid inclusion proof"}</h3><ol>{state.transcript.map((line) => <li className="hash" key={line}>{line}</li>)}</ol></div>}
  </section>;
}
